import test from 'node:test';
import assert from 'node:assert/strict';
import { buildIssueConsoleModel, clientCommunicationDraft, filterDiagnostics, wallboardSubset } from '../statusViewModel.ts';
import type { ProviderStatus, StatusPayload } from '../types.ts';
const provider = (id: string, service: ProviderStatus['service_state'], source: ProviderStatus['source_state'], tags: string[] = [], priority = 1): ProviderStatus => ({ id, name: id, category: 'Cloud', status: service, color: service === 'major' ? 'red' : service === 'degraded' ? 'amber' : service === 'operational' ? 'green' : 'blue', service_state: service, source_state: source, attention: service === 'major' ? 'critical' : service === 'degraded' ? 'action' : source === 'available' ? 'informational' : 'watch', ok: source === 'available', source: `https://${id}.test`, priority, tags, services: ['Mail'] });
const payload = (providers: ProviderStatus[], incidents: StatusPayload['incidents'] = [], changes: StatusPayload['changes'] = []): StatusPayload => ({ schema_version: 2, generated_at: '2026-01-01T00:00:00Z', summary: { service_overall: 'unknown', source_overall: 'limited', active_incident_count: incidents.length, affected_provider_count: new Set(incidents.map(x => x.providerId)).size, confirmed_operational_count: providers.filter(x => x.service_state === 'operational').length, degraded_count: providers.filter(x => x.service_state === 'degraded').length, major_count: providers.filter(x => x.service_state === 'major').length, unknown_count: providers.filter(x => x.service_state === 'unknown').length, limited_count: providers.filter(x => x.source_state === 'limited').length, unavailable_count: providers.filter(x => x.source_state === 'unavailable').length, disabled_count: providers.filter(x => x.source_state === 'disabled').length, pending_count: 0, stale_count: 0, provider_total: providers.length, enabled_provider_count: providers.filter(x => x.source_state !== 'disabled').length, coverage_percent: 25, confirmed_operational_percent: 25 }, providers, incidents, changes, history: changes });
const incident = { id: 'a:outage', providerId: 'a', provider: 'Alpha', category: 'Cloud', title: 'Mail outage', note: 'Mail delivery delayed', source: 'Official', url: 'https://a.test', time: '', color: 'red' as const, service_state: 'major' as const, attention: 'critical' as const, priority: 8, affected_service: 'Mail' };
test('attention ordering prioritizes major, degraded, changed, then operational', () => { const m = buildIssueConsoleModel(payload([provider('ok', 'operational', 'available'), provider('gap', 'unknown', 'unavailable'), provider('bad', 'degraded', 'available'), provider('major', 'major', 'available')]), 'v'); assert.deepEqual(m.diagnostics.map(x => x.id), ['major', 'bad', 'gap', 'ok']); });
test('search covers provider, tag, service and incident detail', () => { const m = buildIssueConsoleModel(payload([provider('a', 'major', 'available', ['identity'])], [incident]), 'v'); for (const q of ['a', 'identity', 'mail', 'delivery'])
    assert.equal(filterDiagnostics(m.diagnostics, q, []).length, 1); });
test('filter combinations and source semantics are explicit', () => { const m = buildIssueConsoleModel(payload([provider('a', 'unknown', 'limited', ['security']), provider('b', 'operational', 'available')]), 'v'); assert.equal(filterDiagnostics(m.diagnostics, '', ['limited', 'security']).length, 1); assert.equal(m.summary.confirmed_operational_count, 1); });
test('draft is cautious and wallboard excludes stable informational', () => { const m = buildIssueConsoleModel(payload([provider('a', 'major', 'available'), provider('b', 'operational', 'available')], [incident]), 'v'); const draft = clientCommunicationDraft(incident); assert.match(draft, /DRAFT/); assert.match(draft, /not been confirmed/); assert.deepEqual(wallboardSubset(m).map(x => x.id), ['a']); });
test('duplicate providers fail', () => assert.throws(() => buildIssueConsoleModel(payload([provider('a', 'unknown', 'limited'), provider('a', 'major', 'available')]), 'v'), /Duplicate/));
