import test from 'node:test';import assert from 'node:assert/strict';
import { dataAge, formatAge, paginate, parseWallboardSettings, providerPageSize, rotationAllowed, STALE_CRITICAL_MS, STALE_WARNING_MS } from '../wallboardConfig.ts';
test('query parameters override saved settings',()=>{const x=parseWallboardSettings('?view=wallboard&screen=sources&rotate=45&density=compact',{view:'operator',screen:'heads-up'});assert.deepEqual(x,{view:'wallboard',screen:'sources',rotateSeconds:45,density:'compact'})});
test('saved settings apply without query and invalid values safely fall back',()=>{assert.equal(parseWallboardSettings('',{view:'wallboard'}).view,'wallboard');const x=parseWallboardSettings('?view=nope&screen=nope&density=nope&rotate=nope');assert.equal(x.view,'operator');assert.equal(x.screen,'heads-up');assert.equal(x.rotateSeconds,30)});
test('rotation supports zero and clamps bounded values',()=>{assert.equal(parseWallboardSettings('?rotate=0').rotateSeconds,0);assert.equal(parseWallboardSettings('?rotate=1').rotateSeconds,20);assert.equal(parseWallboardSettings('?rotate=999').rotateSeconds,300)});
test('rotation pause and reduced-motion behavior are deterministic',()=>{assert.equal(rotationAllowed(30,false,false,false),true);assert.equal(rotationAllowed(30,true,false,false),false);assert.equal(rotationAllowed(30,false,true,false),false);assert.equal(rotationAllowed(30,false,true,true),true);assert.equal(rotationAllowed(0,false,false,true),false)});
test('provider page sizes cover TV matrix',()=>{assert.equal(providerPageSize(3840,2160,'comfortable'),48);assert.equal(providerPageSize(1920,1080,'comfortable'),30);assert.equal(providerPageSize(1366,768,'comfortable'),24);assert.equal(providerPageSize(1280,720,'compact'),30)});
test('pagination includes all 90 providers exactly once',()=>{const values=Array.from({length:90},(_,i)=>i);const pages=paginate(values,30);assert.equal(pages.length,3);assert.deepEqual(pages.flat(),values)});
test('stale thresholds and future generation are explicit',()=>{const now=Date.parse('2026-01-01T02:00:00Z');assert.equal(dataAge(new Date(now-STALE_WARNING_MS+1).toISOString(),now).state,'normal');assert.equal(dataAge(new Date(now-STALE_WARNING_MS).toISOString(),now).state,'warning');assert.equal(dataAge(new Date(now-STALE_CRITICAL_MS-1).toISOString(),now).state,'critical');assert.equal(dataAge(new Date(now+360000).toISOString(),now).state,'invalid');assert.match(formatAge(120000),/2 minutes/) });
