import test from 'node:test';
import assert from 'node:assert/strict';
import { colorFromText, compareSnapshots, fetchSource, newestStatuspageUpdate, parseLimitedMicrosoft, parseRss, parseStatuspage, readBoundedBody, recentRssIncident, safeLoadProvider, summarizeProviders, validatePayload } from '../update-status.mjs';
const provider = { id: 'test', name: 'Test', category: 'Cloud', url: 'https://status.test/api', sourceType: 'statuspage', priority: 90, criticality: 'high' };
const response = (body, status = 200, type = 'application/json', headers = {}) => new Response(body, { status, headers: { 'content-type': type, ...headers } });
const mock = value => { globalThis.fetch = async () => value; };
test('severity normalization', () => { assert.equal(colorFromText('major outage'), 'red'); assert.equal(colorFromText('degraded'), 'amber'); assert.equal(colorFromText('operational'), 'green'); assert.equal(colorFromText('mystery'), 'blue'); });
test('newest Statuspage update selected', () => assert.equal(newestStatuspageUpdate([{ body: 'new', updated_at: '2026-01-02Z' }, { body: 'old', updated_at: '2026-01-01Z' }]).body, 'new'));
test('Statuspage emits explicit available service state', async () => { mock(response(JSON.stringify({ status: { description: 'Operational' }, incidents: [] }))); const r = await parseStatuspage(provider); assert.equal(r.service_state, 'operational'); assert.equal(r.source_state, 'available'); });
test('Statuspage incident is major and resolved/maintenance excluded', async () => { mock(response(JSON.stringify({ status: { description: 'Operational' }, incidents: [{ name: 'Outage', impact: 'major', status: 'investigating', incident_updates: [{ body: 'down' }] }, { name: 'Done', impact: 'minor', status: 'resolved', incident_updates: [] }, { name: 'Maintenance', status: 'scheduled', incident_updates: [] }] }))); const r = await parseStatuspage(provider); assert.equal(r.incidents.length, 1); assert.equal(r.service_state, 'major'); });
test('malformed JSON is source unavailable, not outage', async () => { mock(response('{bad')); const r = await parseStatuspage(provider); assert.equal(r.source_state, 'unavailable'); assert.equal(r.service_state, 'unknown'); });
test('content type mismatch is unavailable and not retried', async () => { let calls = 0; const r = await fetchSource(provider, 'application/json', async () => { calls++; return response('<html>', 200, 'text/html'); }, async () => { }); assert.equal(r.ok, false); assert.equal(calls, 1); assert.match(r.log.error, /content-type/); });
test('valid XML and text fallback accepted', async () => { for (const type of ['application/rss+xml', 'application/xml', 'text/plain'])
    assert.equal((await fetchSource(provider, 'application/rss+xml', async () => response('<rss/>', 200, type))).ok, true); });
test('valid HTML and invalid JSON HTML', async () => { assert.equal((await fetchSource(provider, 'text/html', async () => response('<p>x</p>', 200, 'text/html'))).ok, true); assert.equal((await fetchSource(provider, 'application/json', async () => response('<p>x</p>', 200, 'text/html'))).ok, false); });
test('under-limit and UTF-8 multibyte bodies decode', async () => assert.equal(await readBoundedBody(response('€')), '€'));
test('over-limit Content-Length rejects before reading', async () => await assert.rejects(readBoundedBody(response('x', 200, 'text/plain', { 'content-length': '99' }), 2), /Content-Length/));
test('stream exceeding limit rejects', async () => await assert.rejects(readBoundedBody(response('abcdef'), 3), /stream exceeded/));
test('missing Content-Length reads safely', async () => assert.equal(await readBoundedBody(response('abc', 200, 'text/plain')), 'abc'));
test('aborted stream rejects', async () => { const c = new AbortController(); c.abort(); await assert.rejects(readBoundedBody(response('abc'), 99, c.signal), /Aborted/); });
test('one retry on transient HTTP and attempt logs retained', async () => { let n = 0; const r = await fetchSource(provider, 'application/json', async () => ++n === 1 ? response('{}', 503) : response('{}'), async () => { }); assert.equal(n, 2); assert.equal(r.logs.length, 2); });
test('network error retries once', async () => { let n = 0; const r = await fetchSource(provider, 'application/json', async () => { if (++n === 1)
    throw new TypeError('reset'); return response('{}'); }, async () => { }); assert.equal(r.ok, true); assert.equal(n, 2); });
test('permanent HTTP and oversized response do not retry', async () => { for (const value of [response('{}', 404), response('abcd', 200, 'application/json', { 'content-length': '9999999' })]) {
    let n = 0;
    await fetchSource(provider, 'application/json', async () => { n++; return value; }, async () => { });
    assert.equal(n, 1);
} });
test('Retry-After delay is capped', async () => { let delay = 0, n = 0; await fetchSource(provider, 'application/json', async () => ++n === 1 ? response('{}', 429, 'application/json', { 'retry-after': '999' }) : response('{}'), async (ms) => { delay = ms; }); assert.equal(delay, 1500); });
test('RSS age, future tolerance and dedupe', async () => { const item = (t, d) => `<item><title>${t}</title><description>service outage</description><pubDate>${d}</pubDate></item>`; mock(response(`<rss>${item('API outage', new Date().toUTCString())}${item('API outage update', new Date().toUTCString())}${item('Old outage', '2020-01-01')}</rss>`, 200, 'application/rss+xml')); assert.equal((await parseRss({ ...provider, sourceType: 'rss' })).incidents.length, 1); const base = { title: 'outage', note: 'down', status: '', rawTime: new Date(Date.now() + 240000).toISOString(), color: 'red' }; assert.equal(recentRssIncident(base, 1), true); assert.equal(recentRssIncident({ ...base, rawTime: new Date(Date.now() + 360000).toISOString() }, 1), false); });
test('Microsoft and disabled providers use explicit states', async () => { mock(response('{}')); assert.equal((await parseLimitedMicrosoft({ ...provider, id: 'microsoft365', sourceType: 'limited-microsoft' })).source_state, 'limited'); const r = await safeLoadProvider({ ...provider, enabled: false }); assert.equal(r.source_state, 'disabled'); assert.equal(r.service_state, 'unknown'); });
const ps = (id, service_state, source_state) => ({ id, name: id, category: 'c', status: 'x', color: service_state === 'operational' ? 'green' : service_state === 'major' ? 'red' : service_state === 'degraded' ? 'amber' : 'blue', service_state, source_state, attention: 'informational', ok: source_state === 'available', source: 'https://x.test', priority: 1 });
test('summary: all operational, degradation, major and all unavailable', () => { assert.equal(summarizeProviders([ps('a', 'operational', 'available')], []).service_overall, 'operational'); assert.equal(summarizeProviders([ps('a', 'degraded', 'available')], []).service_overall, 'degraded'); assert.equal(summarizeProviders([ps('a', 'major', 'available')], []).service_overall, 'major'); const s = summarizeProviders([ps('a', 'unknown', 'unavailable')], []); assert.equal(s.service_overall, 'unknown'); assert.equal(s.source_overall, 'unavailable'); });
test('mixed summary reconciles and disabled is excluded', () => { const s = summarizeProviders([ps('a', 'operational', 'available'), ps('b', 'unknown', 'limited'), ps('c', 'unknown', 'unavailable'), ps('d', 'unknown', 'disabled')], []); assert.equal(s.enabled_provider_count, 3); assert.equal(s.disabled_count, 1); assert.equal(s.coverage_percent, 33); assert.equal(s.service_overall, 'unknown'); });
test('payload reconciliation validation catches corruption', () => { const providers = [ps('a', 'operational', 'available')]; const base = { schema_version: 2, generated_at: new Date().toISOString(), summary: summarizeProviders(providers, []), providers, incidents: [], changes: [], history: [] }; assert.equal(validatePayload(base), true); assert.throws(() => validatePayload({ ...base, summary: { ...base.summary, provider_total: 9 } }), /mismatch/); });
test('change detection covers new, severity, resolution and source transitions', () => { const oldIncident = { id: 'a:x', providerId: 'a', provider: 'a', title: 'x', service_state: 'degraded', attention: 'action' }; const currentIncident = { ...oldIncident, service_state: 'major', attention: 'critical' }; const prev = { providers: [ps('a', 'degraded', 'available'), ps('b', 'unknown', 'available')], incidents: [oldIncident, { ...oldIncident, id: 'a:gone', title: 'gone' }] }; const cur = { providers: [ps('a', 'major', 'available'), ps('b', 'unknown', 'unavailable')], incidents: [currentIncident, { ...currentIncident, id: 'a:new', title: 'new' }] }; const types = compareSnapshots(prev, cur).map(x => x.type); for (const type of ['incident_new', 'severity_increased', 'incident_resolved', 'source_unavailable'])
    assert.ok(types.includes(type)); });
test('initial snapshot creates no mass changes', () => assert.deepEqual(compareSnapshots(null, { providers: [ps('a', 'major', 'available')], incidents: [] }), []));
